name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your desired region

    - name: Install AWS SAM CLI
      run: |
        sudo apt-get update && \
        sudo apt-get install -y unzip && \
        curl -Lo aws-sam-cli.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip && \
        unzip aws-sam-cli.zip -d sam-installation && \
        sudo ./sam-installation/install && \
        sam --version

    - name: Build and Deploy
      run: |
        sam build && \
        sam deploy --no-confirm-changeset --stack-name go-serverless-app --capabilities CAPABILITY_IAM
